version: '{build}'
skip_tags: true
environment:
  matrix:
    - nodejs_version: 9.11.1
init:
  - git config --global core.autocrlf input
install:
  - ps: 'Install-Product node $env:nodejs_version'
  - set PATH=%APPDATA%\yarn;%PATH%
  - yarn
build: off
test_script:
  - node --version
  - 'echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc'
  - >-
    IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\src\helpers\sheet\secrets MKDIR
    %APPVEYOR_BUILD_FOLDER%\src\hepers\sheet\secrests
  - >-
    echo %SERVICE_ACCOUNT_DATA% >
    %APPVEYOR_BUILD_FOLDER%\src\helpers\sheet\secrets\serviceAccount.json
  - yarn test
cache:
  - '%LOCALAPPDATA%\Yarn'
  - node_modules -> package.json
