version: 2
jobs:
  test:
    docker:
      - image: 'circleci/node:9.11.1'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: yarn install
      - run: node scripts/link-dev-dependencies.js
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: >-
          mkdir -p src/helpers/sheet/secrets && echo $SERVICE_ACCOUNT_DATA >
          src/helpers/sheet/secrets/serviceAccount.json
      - run: yarn test
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    docker:
      - image: 'circleci/node:9.11.1'
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: 'echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc'
      - run:
          name: Publish Package
          command: yarn release
workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: /master/
