version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:7.10'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: yarn install
      - run: node -r @babel/register scripts/link-dev-dependencies.js
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: yarn test
