version: 2
environment:
  PATH: '${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin'
jobs:
  test:
    docker:
      - image: 'circleci/node:latest-browsers'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: yarn install
      - run: node scripts/link-dev-dependencies.js
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: >-
          mkdir -p src/helpers/sheet/secrets && echo $SERVICE_ACCOUNT_DATA >
          src/helpers/sheet/secrets/serviceAccount.json
      - run: yarn test
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    docker:
      - image: 'circleci/node:latest-browsers'
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: 'echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc'
      - add-ssh-keys:
          fingerprints:
            - 'f8:90:0c:73:97:e6:05:36:f8:c7:15:39:3b:46:9a:d0'
            - 'd4:7c:3d:39:70:88:bc:59:da:19:83:c2:01:8a:52:39'
            - '30:92:bd:d1:ee:3f:a4:07:22:c4:c0:11:24:1e:e9:3d'
      - run:
          name: Add known hosts
          command: >-
            mkdir -p $HOME/.ssh && echo
            "|1|SxUcfNX5Zjx+uif5Qyzwj2oupqs=|TV5bWbELoPdwWIAaqJ2QUq5Sa0M=
            ssh-rsa
            AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
            > $HOME/.ssh/known_hosts
      - run:
          name: Configure git defaults
          command: >-
            git config user.email "jon@dais.com" && git config user.name
            "CircleCI"
workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: /master/
